### ISSUE TITLE
Understanding the pipeline

### ISSUE THREAD

**Issue by SURABHI-GUPTA** [edosedgar/mtcnnattack#6]
@edosedgar It would be really helpful if you can explain the steps of the pipeline in short. After applying checkerboard on the face, how projective transform is done ? I didn't get the concept of patch. Is patch the checkerboard or something else ?

**Comment by edosedgar** [comment]
The points are placed over the crosses in a checkerboard. The algorithm fins these points and transform patches according to the position of these crosses. The patch is placed over the checkerboard then.

**Comment by SURABHI-GUPTA** [comment]
@edosedgar on what basis are these points transformed ?

**Comment by edosedgar** [comment]
On the basis of warp transform. You have two sets each consisting of 4 coordinates: for a source and for a destination. Based on the total of 8 points you calculate the warp transform matrix. Since the patch is split into squares of 4 points, we iterate over each quadrangle and calculate the transform matrices. I hope it is clear now. Also, mind to look over the closed issues.
